### ISSUE TITLE
[Android] App crashes when paying

### ISSUE THREAD

**Issue by fimak** [Anton-1408/react-native-cloudpayments#23]
```
FATAL EXCEPTION: main

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

FATAL EXCEPTION: main
Process: com.names.application, PID: 10010
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at java.io.StringReader.<init>(StringReader.java:50)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at ru.cloudpayments.sdk.viewmodel.PaymentProcessViewModel.pay(Unknown Source:15)
	at ru.cloudpayments.sdk.ui.dialogs.PaymentProcessFragment.onViewCreated(Unknown Source:61)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3137)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1901)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1825)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1762)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8377)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

**Comment by yupdevelop** [comment]
Solved the problem by passing some jsonData to initialPaymentData:

```
const PAYMENT_DATA_CARD = {
  publicId: strings.cloudPaymentsId,
  jsonData: JSON.stringify({ name: 'Anton' }),
};

const creditCardForm = CreditCardForm.initialPaymentData(PAYMENT_DATA_CARD);
```

But it looks like you also need to update CloudPayments Android SDK, because the payment doesn't work with the SDK that is a dependency of this library. I used version 1.5.15
